version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: web3
    versions:
    - 5.15.0
    - 5.16.0
    - 5.17.0
    - 5.18.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
